import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Set style for publication-ready plots
plt.style.use('default')
plt.rcParams['figure.dpi'] = 300
plt.rcParams['savefig.dpi'] = 300
plt.rcParams['font.size'] = 12
plt.rcParams['axes.labelsize'] = 12
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['xtick.labelsize'] = 10
plt.rcParams['ytick.labelsize'] = 10
plt.rcParams['legend.fontsize'] = 10

def load_data():
    """Load the CSV files generated by the C++ program"""
    try:
        summary_df = pd.read_csv('results_summary.csv')
        detailed_df = pd.read_csv('results_detailed.csv')
        return summary_df, detailed_df
    except FileNotFoundError as e:
        print(f"Error: {e}")
        print("Please run the C++ report program first to generate CSV files.")
        return None, None

def plot_accuracy_by_criterion(df):
    """Plot accuracy comparison by criterion for each dataset"""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    
    datasets = ['Adult', 'Iris']
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c']
    
    for i, dataset in enumerate(datasets):
        dataset_df = df[df['Dataset'] == dataset]
        criterion_acc = dataset_df.groupby('Criterion')['AvgAccuracy'].mean()
        
        bars = [ax1, ax2][i].bar(criterion_acc.index, criterion_acc.values, 
                                color=colors, alpha=0.8, edgecolor='black', linewidth=0.5)
        [ax1, ax2][i].set_title(f'{dataset} Dataset')
        [ax1, ax2][i].set_ylabel('Average Accuracy')
        [ax1, ax2][i].set_ylim(0, 1)
        [ax1, ax2][i].grid(True, alpha=0.3)
        
        # Add value labels on bars
        for j, v in enumerate(criterion_acc.values):
            [ax1, ax2][i].text(j, v + 0.02, f'{v:.3f}', ha='center', va='bottom')
    
    plt.tight_layout()
    plt.savefig('accuracy_by_criterion.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("Saved: accuracy_by_criterion.png")

def plot_accuracy_by_depth(df):
    """Plot accuracy vs max depth for each criterion"""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    
    datasets = ['Adult', 'Iris']
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c']
    markers = ['o', 's', '^']
    
    for i, dataset in enumerate(datasets):
        dataset_df = df[df['Dataset'] == dataset]
        
        for j, criterion in enumerate(df['Criterion'].unique()):
            criterion_df = dataset_df[dataset_df['Criterion'] == criterion]
            [ax1, ax2][i].plot(criterion_df['MaxDepth'], criterion_df['AvgAccuracy'], 
                              marker=markers[j], label=criterion, linewidth=2, 
                              color=colors[j], markersize=6)
        
        [ax1, ax2][i].set_title(f'{dataset} Dataset')
        [ax1, ax2][i].set_xlabel('Max Depth (0 = No Limit)')
        [ax1, ax2][i].set_ylabel('Average Accuracy')
        [ax1, ax2][i].legend()
        [ax1, ax2][i].grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('accuracy_by_depth.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("Saved: accuracy_by_depth.png")

def plot_complexity_vs_accuracy(df):
    """Plot tree complexity (nodes) vs accuracy"""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    
    datasets = ['Adult', 'Iris']
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c']
    markers = ['o', 's', '^']
    
    for i, dataset in enumerate(datasets):
        dataset_df = df[df['Dataset'] == dataset]
        
        for j, criterion in enumerate(df['Criterion'].unique()):
            criterion_df = dataset_df[dataset_df['Criterion'] == criterion]
            [ax1, ax2][i].scatter(criterion_df['AvgNodes'], criterion_df['AvgAccuracy'], 
                                 label=criterion, alpha=0.7, s=60, color=colors[j], 
                                 marker=markers[j], edgecolors='black', linewidth=0.5)
        
        [ax1, ax2][i].set_title(f'{dataset} Dataset')
        [ax1, ax2][i].set_xlabel('Average Number of Nodes')
        [ax1, ax2][i].set_ylabel('Average Accuracy')
        [ax1, ax2][i].legend()
        [ax1, ax2][i].grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('complexity_vs_accuracy.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("Saved: complexity_vs_accuracy.png")

def plot_training_time(df):
    """Plot training time comparison"""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
    
    datasets = ['Adult', 'Iris']
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c']
    
    for i, dataset in enumerate(datasets):
        dataset_df = df[df['Dataset'] == dataset]
        criterion_time = dataset_df.groupby('Criterion')['AvgTrainingTime(ms)'].mean()
        
        bars = [ax1, ax2][i].bar(criterion_time.index, criterion_time.values, 
                                color=colors, alpha=0.8, edgecolor='black', linewidth=0.5)
        [ax1, ax2][i].set_title(f'{dataset} Dataset')
        [ax1, ax2][i].set_ylabel('Average Training Time (ms)')
        [ax1, ax2][i].grid(True, alpha=0.3)
        
        # Add value labels on bars
        for j, v in enumerate(criterion_time.values):
            [ax1, ax2][i].text(j, v + max(criterion_time.values) * 0.02, 
                              f'{v:.1f}', ha='center', va='bottom')
    
    plt.tight_layout()
    plt.savefig('training_time.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("Saved: training_time.png")

def plot_depth_effect_combined(df):
    """Plot comprehensive depth effect analysis"""
    fig, axes = plt.subplots(2, 3, figsize=(18, 10))
    
    datasets = ['Adult', 'Iris']
    metrics = ['AvgAccuracy', 'AvgNodes', 'AvgTrainingTime(ms)']
    metric_labels = ['Average Accuracy', 'Average Nodes', 'Average Training Time (ms)']
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c']
    markers = ['o', 's', '^']
    
    for i, dataset in enumerate(datasets):
        dataset_df = df[df['Dataset'] == dataset]
        
        for j, (metric, label) in enumerate(zip(metrics, metric_labels)):
            for k, criterion in enumerate(df['Criterion'].unique()):
                criterion_df = dataset_df[dataset_df['Criterion'] == criterion]
                axes[i, j].plot(criterion_df['MaxDepth'], criterion_df[metric], 
                              marker=markers[k], label=criterion, linewidth=2, 
                              color=colors[k], markersize=5)
            
            axes[i, j].set_title(f'{dataset} Dataset - {label}')
            axes[i, j].set_xlabel('Max Depth (0 = No Limit)')
            axes[i, j].set_ylabel(label)
            if j == 0:  # Only show legend for first column
                axes[i, j].legend()
            axes[i, j].grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('depth_effect_analysis.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("Saved: depth_effect_analysis.png")

def plot_performance_comparison_table(df):
    """Create a visual performance comparison table"""
    # Create a pivot table for better visualization
    pivot_data = []
    for dataset in ['Adult', 'Iris']:
        dataset_df = df[df['Dataset'] == dataset]
        for _, row in dataset_df.iterrows():
            pivot_data.append({
                'Dataset': dataset,
                'Criterion': row['Criterion'],
                'MaxDepth': row['MaxDepth'],
                'Accuracy': row['AvgAccuracy'],
                'Nodes': row['AvgNodes'],
                'Time': row['AvgTrainingTime(ms)']
            })
    
    pivot_df = pd.DataFrame(pivot_data)
    
    # Create heatmap for accuracy
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))
    
    for i, dataset in enumerate(['Adult', 'Iris']):
        dataset_data = pivot_df[pivot_df['Dataset'] == dataset]
        heatmap_data = dataset_data.pivot(index='Criterion', columns='MaxDepth', values='Accuracy')
        
        im = [ax1, ax2][i].imshow(heatmap_data.values, cmap='RdYlGn', aspect='auto')
        [ax1, ax2][i].set_title(f'{dataset} Dataset - Accuracy Heatmap')
        [ax1, ax2][i].set_xlabel('Max Depth')
        [ax1, ax2][i].set_ylabel('Criterion')
        [ax1, ax2][i].set_xticks(range(len(heatmap_data.columns)))
        [ax1, ax2][i].set_xticklabels(heatmap_data.columns)
        [ax1, ax2][i].set_yticks(range(len(heatmap_data.index)))
        [ax1, ax2][i].set_yticklabels(heatmap_data.index)
        
        # Add text annotations
        for row in range(len(heatmap_data.index)):
            for col in range(len(heatmap_data.columns)):
                value = heatmap_data.iloc[row, col]
                [ax1, ax2][i].text(col, row, f'{value:.3f}', 
                                  ha='center', va='center', fontsize=10)
    
    plt.tight_layout()
    plt.savefig('performance_heatmap.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("Saved: performance_heatmap.png")

def main():
    """Main function to generate all plots"""
    print("Loading data...")
    summary_df, detailed_df = load_data()
    
    if summary_df is None:
        return
    
    print(f"Loaded {len(summary_df)} summary records")
    print("\nGenerating publication-ready plots...")
    
    # Generate all plots
    plot_accuracy_by_criterion(summary_df)
    plot_accuracy_by_depth(summary_df)
    plot_complexity_vs_accuracy(summary_df)
    plot_training_time(summary_df)
    plot_depth_effect_combined(summary_df)
    plot_performance_comparison_table(summary_df)
    
    print("\nAll plots generated successfully!")
    print("Files saved:")
    print("- accuracy_by_criterion.png")
    print("- accuracy_by_depth.png") 
    print("- complexity_vs_accuracy.png")
    print("- training_time.png")
    print("- depth_effect_analysis.png")
    print("- performance_heatmap.png")
    print("\nReady for LaTeX inclusion!")

if __name__ == "__main__":
    main()
